env:
  RAILS_ENV: test
  CC_TEST_REPORTER_ID: f39e060a8b1a558ebd8aff75d5b9760bf1ae98f3f85d628ae28814f3c66438cd
  APP_PROTOCOL: http://
  APP_DOMAIN: localhost:3000
  TIMBER: dummy
  SEND_LOGS_TO_TIMBER: false
  SENDGRID_USERNAME_ACCEL: dummy
  SENDGRID_PASSWORD_ACCEL: dummy
  HEROKU_APP_URL: practicaldev.herokuapp.com
  SECRET_KEY_BASE: dummydummydummy
  GITHUB_KEY: dummy
  GITHUB_SECRET: dummy
  COVERAGE_REPORTS_TOTAL: 4

install: |
  sudo apt update -y
  sudo apt install wget -y

  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

  wget --quiet -O - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  echo "deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

  sudo apt update -y

  sudo apt install -y \
    software-properties-common build-essential \
    gcc g++ make cmake unzip libffi-dev \
    libcurl4-openssl-dev libssl-dev zlib1g-dev \
    postgresql-13 postgresql-contrib libpq-dev \
    imagemagick \
    redis-server \
    elasticsearch-oss \
    chromium-chromedriver libnss3 xdg-utils

  sudo snap install chromium

  sudo systemctl enable elasticsearch
  sudo systemctl start elasticsearch
  sudo su postgres -c 'createuser ubuntu --superuser'

  wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  nvm install 12.16
  npm install -g yarn

  sudo apt-add-repository -y ppa:rael-gc/rvm
  sudo apt-get update
  sudo apt-get install rvm -y
  sudo chown -R ubuntu /usr/share/rvm
  sudo usermod -a -G rvm ubuntu
  source /etc/profile.d/rvm.sh
  rvm install "ruby-2.7.1"

  echo "gem: --no-document" >> ~/.gemrc
  gem install bundler

  bundle config set with 'development test'
  bundle config set path 'vendor/bundle'

  bundle install --jobs 4 --retry 3
  bundle exec rails db:create
  bundle exec rails db:schema:load
  bundle exec rails search:setup
  bundle exec spring binstub --all

  yarn install --ignore-engines
  bundle exec rails webpacker:compile
  RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update

setup: |
  bundle install --deployment --jobs 4 --retry 3 --without development production
  bundle exec rails webpacker:compile

test_suite:
  command: bundle exec rspec

  files:
    - spec/**/*_spec.rb