env:
  GITHUB_KEY: 1
  GITHUB_SECRET: 1

install: |
  sudo add-apt-repository ppa:apt-fast/stable
  sudo apt update -y

  echo debconf apt-fast/maxdownloads string 16 | debconf-set-selections
  echo debconf apt-fast/dlflag boolean true | debconf-set-selections
  echo debconf apt-fast/aptmanager string apt-get | debconf-set-selections
  sudo apt-get -y install apt-fast

  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list

  wget --quiet -O - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  echo "deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

  curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

  sudo apt update -y

  time sudo apt install -y \
    build-essential gcc g++ make cmake unzip \
    libcurl4-openssl-dev libssl-dev \
    postgresql postgresql-contrib libpq-dev \
    imagemagick \
    redis-server \
    elasticsearch-oss \
    nodejs yarn

  yarn config set ignore-engines true

  sudo systemctl start elasticsearch
  sudo su postgres -c 'createuser kmcd --superuser'

  wget -O ruby-install-0.7.0.tar.gz https://github.com/postmodern/ruby-install/archive/v0.7.0.tar.gz
  tar -xzvf ruby-install-0.7.0.tar.gz
  cd ruby-install-0.7.0
  sudo make install
  cd ..
  rm -Rf ruby-install*

  wget -O chruby-0.3.9.tar.gz https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz
  tar -xzvf chruby-0.3.9.tar.gz
  cd chruby-0.3.9/
  sudo make install
  cd ..
  rm -Rf chruby-0.3.*

  time ruby-install ruby 2.7.1 --no-reinstall

  echo "source /usr/local/share/chruby/chruby.sh" >> ~/.bashrc
  echo "source /usr/local/share/chruby/auto.sh" >> ~/.bashrc
  source /usr/local/share/chruby/chruby.sh
  chruby 2.7.1

  echo "gem: --no-document" >> ~/.gemrc
  gem install bundler
  time ./bin/setup

setup: |
  bundle install

test_suite:
  command: bundle exec rspec

  files:
    - spec/**/*_spec.rb
