env:
  COVERAGE:           false
  DATABASE_URL_TEST:  postgres:///Forem_test
  RAILS_ENV:          test

install: |
  # clear_cache: 078fb894b0ba0879aa670b971a3dbb85
  echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections

  sudo apt update -y
  sudo apt install wget -y

  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

  wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

  sudo apt update -y

  sudo apt install -y \
    software-properties-common build-essential \
    gcc g++ make cmake unzip libffi-dev \
    libcurl4-openssl-dev libssl-dev zlib1g-dev \
    postgresql-13 postgresql-contrib libpq-dev \
    imagemagick \
    redis-server \
    chromium-chromedriver libnss3 xdg-utils google-chrome-stable

  sudo su postgres -c 'createuser ubuntu --superuser'
  sudo su -c 'echo "host all all 127.0.0.1/32 trust" >> /etc/postgresql/13/main/pg_hba.conf'
  sudo service postgresql restart

  bash <( wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh )
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use
  nvm install 14.14
  npm install -g yarn

  sudo apt-add-repository -y ppa:rael-gc/rvm
  sudo apt-get update
  sudo apt-get install rvm -y
  sudo chown -R ubuntu /usr/share/rvm
  sudo usermod -a -G rvm ubuntu
  source /etc/profile.d/rvm.sh
  rvm install "ruby-2.7.2"

  echo "source ~/.bashrc" >> ~/.bash_profile
  echo "source ~/.nvm/nvm.sh" >> ~/.bash_profile
  echo "nvm use 14.14" >> ~/.bash_profile
  echo "source /etc/profile.d/rvm.sh" >> ~/.bash_profile

  echo "gem: --no-document" >> ~/.gemrc
  gem install bundler

  cp .env_sample .env

  bundle install
  bundle exec spring binstub --all

  bin/rails db:create
  bin/rails db:schema:load
  bin/rails webdrivers:chromedriver:update

  yarn install --ignore-engines
  bin/rails webpacker:compile

setup: |
  yarn install --ignore-engines
  bundle install
  bin/rails db:migrate
  bin/rails webpacker:compile
  bin/rails webdrivers:chromedriver:update

test_suite:
  env:
    DISABLE_SPRING: true

  command: bin/rspec

  files:
    # - spec/**/*_spec.rb
    - spec/services/feeds/import_spec.rb
    - spec/models/user_spec.rb
    - spec/requests/notifications_spec.rb
    # - spec/system/comments/user_fills_out_comment_spec.rb
    # - spec/models/article_spec.rb
    # - spec/services/articles/feeds/large_forem_experimental_spec.rb
    # - spec/requests/listings_spec.rb
    # - spec/system/notifications/notifications_page_spec.rb
    # - spec/system/comments/user_edits_a_comment_spec.rb
    # - spec/requests/comments_spec.rb
    # - spec/services/authentication/authenticator_spec.rb
    # - spec/requests/dashboard_spec.rb
    # - spec/requests/stories_index_spec.rb
    # - spec/requests/user/user_settings_spec.rb
    # - spec/services/broadcasts/welcome_notification/generator_spec.rb