install: |
  # clear_cache: 5c630ee7fe41721357edd4016c049540
  echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections

  sudo apt update -y
  sudo apt install wget -y

  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

  wget --quiet -O - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  echo "deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

  wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

  sudo apt update -y

  sudo apt install -y \
    software-properties-common build-essential \
    gcc g++ make cmake unzip libffi-dev \
    libcurl4-openssl-dev libssl-dev zlib1g-dev \
    postgresql-13 postgresql-contrib libpq-dev \
    imagemagick \
    redis-server \
    elasticsearch-oss \
    chromium-chromedriver libnss3 xdg-utils google-chrome-stable

  sudo systemctl enable elasticsearch
  sudo systemctl start elasticsearch
  sudo su postgres -c 'createuser ubuntu --superuser'

  bash <( wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh )
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use
  nvm install 14.14
  npm install -g yarn
  yarn install --ignore-engines

  sudo apt-add-repository -y ppa:rael-gc/rvm
  sudo apt-get update
  sudo apt-get install rvm -y
  sudo chown -R ubuntu /usr/share/rvm
  sudo usermod -a -G rvm ubuntu
  source /etc/profile.d/rvm.sh
  rvm install "ruby-2.7.2"

  echo "source ~/.bashrc" >> ~/.bash_profile
  echo "source ~/.nvm/nvm.sh" >> ~/.bash_profile
  echo "nvm use 14.14" >> ~/.bash_profile
  echo "source /etc/profile.d/rvm.sh" >> ~/.bash_profile

  echo "gem: --no-document" >> ~/.gemrc
  gem install bundler

  cp .env_sample .env

  bundle install
  bundle exec rails db:create
  bundle exec rails db:schema:load
  bundle exec rails search:setup
  bundle exec spring binstub --all

  bundle exec rails webpacker:compile
  RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update

setup: |
  yarn install --ignore-engines
  bundle install
  bundle exec rails db:migrate
  bundle exec rails webpacker:compile
  RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update

test_suite:
  env:
    COVERAGE: false
    DISABLE_SPRING: true

  command: bundle exec rspec

  files:
    # - spec/**/*_spec.rb
    - spec/services/feeds/import_spec.rb
    - spec/models/user_spec.rb
    - spec/requests/notifications_spec.rb
    - spec/system/comments/user_fills_out_comment_spec.rb
    - spec/models/article_spec.rb
    # - spec/services/articles/feeds/large_forem_experimental_spec.rb
    # - spec/requests/listings_spec.rb
    # - spec/system/notifications/notifications_page_spec.rb
    # - spec/system/comments/user_edits_a_comment_spec.rb
    # - spec/requests/comments_spec.rb
    # - spec/services/authentication/authenticator_spec.rb
    # - spec/requests/dashboard_spec.rb
    # - spec/requests/stories_index_spec.rb
    # - spec/requests/user/user_settings_spec.rb
    # - spec/services/broadcasts/welcome_notification/generator_spec.rb