env:
  RAILS_ENV: test
  APP_PROTOCOL: http://
  APP_DOMAIN: localhost:3000

install: |
  sudo apt update -y
  sudo apt install wget -y

  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

  wget --quiet -O - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  echo "deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

  wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

  sudo apt update -y

  sudo apt install -y \
    software-properties-common build-essential \
    gcc g++ make cmake unzip libffi-dev \
    libcurl4-openssl-dev libssl-dev zlib1g-dev \
    postgresql-13 postgresql-contrib libpq-dev \
    imagemagick \
    redis-server \
    elasticsearch-oss \
    chromium-chromedriver libnss3 xdg-utils google-chrome-stable

  sudo systemctl enable elasticsearch
  sudo systemctl start elasticsearch
  sudo su postgres -c 'createuser ubuntu --superuser'

  wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  nvm install 14.14
  npm install -g yarn

  sudo apt-add-repository -y ppa:rael-gc/rvm
  sudo apt-get update
  sudo apt-get install rvm -y
  sudo chown -R ubuntu /usr/share/rvm
  sudo usermod -a -G rvm ubuntu
  source /etc/profile.d/rvm.sh
  rvm install "ruby-2.7.1"

  echo "gem: --no-document" >> ~/.gemrc
  gem install bundler

  bundle install
  bundle exec rails db:create
  bundle exec rails db:schema:load
  bundle exec rails search:setup
  bundle exec spring binstub --all

  yarn install --ignore-engines
  bundle exec rails webpacker:compile
  RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update

setup: |
  bundle install
  bundle exec rails db:migrate
  yarn install --ignore-engines
  bundle exec rails webpacker:compile
  RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update

test_suite:
  command: bundle exec rspec

  files:
    - spec/**/*_spec.rb