install: |
  echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections

  sudo apt update -y
  sudo apt install wget -y

  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

  wget --quiet -O - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  echo "deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

  wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

  sudo apt update -y

  sudo apt install -y \
    software-properties-common build-essential \
    gcc g++ make cmake unzip libffi-dev \
    libcurl4-openssl-dev libssl-dev zlib1g-dev \
    postgresql-13 postgresql-contrib libpq-dev \
    imagemagick \
    redis-server \
    elasticsearch-oss \
    chromium-chromedriver libnss3 xdg-utils google-chrome-stable

  sudo systemctl enable elasticsearch
  sudo systemctl start elasticsearch
  sudo su postgres -c 'createuser ubuntu --superuser'

  bash <( wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh )
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use
  nvm install 14.14
  npm install -g yarn
  yarn install --ignore-engines

  sudo apt-add-repository -y ppa:rael-gc/rvm
  sudo apt-get update
  sudo apt-get install rvm -y
  sudo chown -R ubuntu /usr/share/rvm
  sudo usermod -a -G rvm ubuntu
  source /etc/profile.d/rvm.sh
  rvm install "ruby-2.7.2"

  echo "source ~/.bashrc" >> ~/.bash_profile
  echo "source ~/.nvm/nvm.sh" >> ~/.bash_profile
  echo "nvm use 14.14" >> ~/.bash_profile
  echo "source /etc/profile.d/rvm.sh" >> ~/.bash_profile

  echo "gem: --no-document" >> ~/.gemrc
  gem install bundler

  cp .env_sample .env

  bundle install
  bundle exec rails db:create
  bundle exec rails db:schema:load
  bundle exec rails search:setup
  bundle exec spring binstub --all

  bundle exec rails webpacker:compile
  RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update

setup: |
  yarn install --ignore-engines
  bundle install
  bundle exec rails db:migrate
  bundle exec rails webpacker:compile
  RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update

test_suite:
  command: bundle exec rspec

  files:
    # - spec/**/*_spec.rb
    - spec/helpers/social_image_helper_spec.rb
    - spec/uploaders/article_image_uploader_spec.rb
    - spec/mailers/verification_mailer_spec.rb
    - spec/lib/data_update_scripts/append_collective_noun_to_community_name_spec.rb
    - spec/requests/video_states_update_spec.rb
    - spec/requests/tag_adjustments_spec.rb
    - spec/services/exporter/comments_spec.rb
    - spec/lib/data_update_scripts/resync_unpublished_articles_comments_elasticsearch_document_spec.rb
    - spec/models/badge_spec.rb
    - spec/decorators/article_decorator_spec.rb
    - spec/services/color/accessibility_spec.rb
    - spec/requests/admin/users_manage_spec.rb
    - spec/services/twilio/get_jwt_token_spec.rb
    - spec/mailers/digest_mailer_spec.rb
    - spec/models/poll_skip_spec.rb
    - spec/services/slack/messengers/article_fetched_feed_spec.rb
    - spec/helpers/application_helper_spec.rb
    - spec/lib/data_update_scripts/make_tags_with_mods_supported_spec.rb
    - spec/workers/reactions/bust_reactable_cache_worker_spec.rb
    - spec/policies/reaction_policy_spec.rb
    - spec/services/badges/award_contributor_spec.rb
    - spec/workers/slack/messengers/worker_spec.rb
    - spec/services/profiles/update_spec.rb
    - spec/models/podcast_ownership_spec.rb
    - spec/requests/admin/configs_spec.rb